language: node_js

node_js:
- '0.10'
- '0.11'

deploy:
  provider: npm
  email: mark@segfawlt.net
  api_key:
    secure: eVXNU4NfNiCkmRJMe9HU/bycHXGkPTGgi+g7MgGJHsHi0m1Dtzie/3kLAzeajwLv/bRq3pz3IxDzb1m+I4L0+XTzq9sxtKR+TFwqkv1HZ94+7ELuMPW1OhIESWzvICOy57d659/YAFS8VUa+L8J+sPX1ctp72cUdJ6xK8mWV4FU=
  on:
    tags: true
    repo: hightail/smartling-sdk
    all_branches: true
